name: Build, and publish spec to GitHub Pages and /TR/

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/04/24-tt-minutes.html#3a2f
          W3C_BUILD_OVERRIDE: |
            specStatus: NOTE

# not set 'warning' to BUILD_FAIL_ON (not to cause error by bikeshed warning?)

